### ISSUE TITLE
No action when press negative button from EasyPermissions.requestPermissions()

### ISSUE THREAD

**Issue by samvgorode** [googlesamples/easypermissions#204]
## Basic Information

Device type: xiaomi redmi 3s;
OS version:  android 6.0.1;
EasyPermissions version: version 1.1.2 and 1.1.3;

## Describe the problem

No action when press negative button from EasyPermissions.requestPermissions()  inside fragment.

I expected that dialog will appear again.

In version 1.1.1 everything is OK.

All methods are from the box, nothing new.

**Comment by samtstern** [comment]
@samvgorode are you using `android.support.v4.app.Fragment` or `android.app.Fragment`?  Does the issue still exist in `1.1.3`?

**Comment by samvgorode** [comment]
I use android.support.v4.app.Fragment. I downgraded version to 1.1.1. I'll check 1.1.2 today.

**Comment by samtstern** [comment]
https://github.com/googlesamples/easypermissions/releases/tag/1.1.3

Your issue should be solved by 1.1.3, I will close this and you can re-open it if that's not the case.

**Comment by samvgorode** [comment]
with version 1.1.3 I still face that problem, as described above. Only 1.1.1 works properly for me. I stay with it.

**Comment by samtstern** [comment]
@samvgorode do you override `onActivityResult()` in your `Activity` or in your `Fragment`?  If so do you call the appropriate `EasyPermissions` method as well as the `super` method?

**Comment by samvgorode** [comment]
I override `onActivityResult()` inside `android.support.v4.app.Fragment`

`private static final int RC_BODY_SENSORS = 124;`

```
@AfterPermissionGranted (RC_BODY_SENSORS)
    public void initHelpers() {
        if (hasWritePermission()) {
          //some logic here
        } else {
            EasyPermissions.requestPermissions(
                    PersonalInfoFragment.this,
                    "Need to read your body sensors data",
                    RC_BODY_SENSORS,
                    Manifest.permission.BODY_SENSORS
            );
        }
    }
```

```
 @Override
    public void onRequestPermissionsResult(int requestCode,
                                           @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }
```

```
@Override
    public void onPermissionsDenied(int requestCode, @NonNull List<String> perms) {
        if (EasyPermissions.somePermissionPermanentlyDenied(this, perms)) {
            new AppSettingsDialog.Builder(this).build().show();
        } if (requestCode == 124) {
            EasyPermissions.requestPermissions(
                    this,
                    "Need to read your body sensors data",
                    RC_BODY_SENSORS,
                    Manifest.permission.BODY_SENSORS);
        }
    }
```

 ```
@Override
    public void onPermissionsGranted(int requestCode, @NonNull List<String> perms) {
        // my logic
    }
```

```
private boolean hasWritePermission() {
        return getContext() != null && EasyPermissions.hasPermissions(getContext(), Manifest
                .permission.BODY_SENSORS);
    }
```

**Comment by samtstern** [comment]
Ok here are all the changes between `1.1.1` and now:
https://github.com/googlesamples/easypermissions/compare/2189d2f...master

And to clarify, you want to keep asking the user for permission every time it is denied?

The only thing I can think of is that maybe the code to prevent the dialog from being shown twice is actually the problem here.

**Comment by ernestkamara** [comment]
Did you follow the examples in the sample app?

Have you tried to override `onActivityResult()` in your Activity and forward the results to your fragment's `onActivityResult()`?

```   
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Fragment fragment = getSupportFragmentManager().findFragmentById(some_fragment_id);
        fragment.onActivityResult(requestCode, resultCode, data);
    }
```
You may have to also change your host/ context when for the `AppSettingsDialog` from by replacing 

```
new AppSettingsDialog.Builder(this).build().show();
```
 with  

```
new AppSettingsDialog.Builder(getActivity).build().show();
```

Hope it works for you. Otherwise feel free to share a copy of your project so that i can debug the issue for you.

**Comment by SUPERCILEX** [comment]
@samvgorode I can't repro, could you try forking this repo and changing the [MainFragment](https://github.com/googlesamples/easypermissions/blob/master/app/src/main/java/pub/devrel/easypermissions/sample/MainFragment.java) to reproduce your bug?

**Comment by xuanzhui** [comment]
As @samtstern said there was code to prevent the dialog from being shown twice (check `ActivityPermissionHelper` --> `showRequestPermissionRationale`).   
The workaround is to implement `EasyPermissions.RationaleCallbacks`, and override `onRationaleDenied`:

```
@Override
public void onRationaleDenied(int requestCode) {
    if (requestCode == REQUEST_WRITE_PERMISSION) {
        ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_WRITE_PERMISSION);
    }
}
```

**Comment by samtstern** [comment]
@samvgorode since it's been a while since anyone commented on this thread I am going to close it.  Hopefully you found your answer!
